when:
  - event: [push, manual]

labels:
  platform: linux/amd64

steps:
  - name: build-windows
    image: powershell
    commands:
      - Set-Location image-process
      - python -m pip install --upgrade pip
      - python -m pip install uv
      - uv sync --dev
      - make package-windows-ps
      - Get-ChildItem packages